### ISSUE TITLE
Is there a schematic of the PyTechBrain board?

### ISSUE THREAD

**Issue by RandoSY** [ABIX-Edukacja/PyTechBrain#10]
I would like to see how the sensors are connected.

**Comment by abixadamj** [comment]
Sorry, I don't have it - my friend, who made the board directly...
Adam Jurkiewicz · Python 3 · fastAPI · Docker · Git (GitHub, Gogs) · Linux Debian · GCP · AWS · Azure
https://www.linkedin.com/in/adam-jurkiewicz-python-linux/ <https://www.linkedin.com/in/adam-jurkiewicz-python-linux/> 
https://profile.codersrank.io/user/abixadamj/ <https://profile.codersrank.io/user/abixadamj/> 
<https://www.linkedin.com/in/adam-jurkiewicz-python-linux/> 
RandoSY wrote:
I would like to see how the sensors are connected.

**Comment by abixadamj** [comment]
I have something like this:

[ABIX-PYTECHBRAIN-01.pdf](https://github.com/ABIX-Edukacja/PyTechBrain/files/9362999/ABIX-PYTECHBRAIN-01.pdf)

and

![schemat_pion](https://user-images.githubusercontent.com/5088643/185144555-3d716dc8-a98e-49e9-8072-3399dbc25ada.png)

**Comment by RandoSY** [comment]
Thank you for the courtesy of your prompt reply.

Since you were kind enough to share your source,  I thought I might make the slight modification that would support this shield,/Arduino UNO clone combination.  

I was able to get you Python library to see the Firmata image I had running on the Arduino.

`C:\Users\randa\Desktop\PyTechBrain Poland\PyTechBrain-master\Python_examples>python
Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyTechBrain import *
>>> from time import sleep
**>>> result = PyTechBrain()**
Initializing object: <PyTechBrain.PyTechBrain.PyTechBrain object at 0x000002D2EF85BCA0>.`

``
**`>>> result.board_init("COM3")**

pymata_aio Version 2.34 Copyright (c) 2015-2018 Alan Yorinks All rights reserved.

Using COM Port:COM3`

![Hf89ad16a157943b19d6b157a7ef39a71q](https://user-images.githubusercontent.com/609947/185213729-a6956717-2ae5-4dd5-a85f-f5d14eb50615.jpg)

Very similar idea, just slightly different pin assignments.
