### ISSUE TITLE
FirmataPlus problem...

### ISSUE THREAD

**Issue by abixadamj** [ABIX-Edukacja/PyTechBrain#7]
Chciałem przetestować: 
https://github.com/MrYsLab/pymata-aio/wiki/Uploading-FirmataPlus-to-Arduino

Wrzuciłem FirmataPlus i dziwnie zachowują się diody LED digital : RED, Yellow, Green - słabo świecą i off nie powoduje końca świcenia.. świecą ciągle...

**Comment by wrata** [comment]
Tak dzieje się w przypadku, gdy płytka zawiera FirmataPlus i wykorzystujemy program pisany dla StandardFirmata. Też miałem ten problem i wróciłem do wcześniejszej wersji firmwaru. 
Należy zmienić początek kodu programu i zaimportować odpowiednie moduły. Przetestowałem to, wkrótce wyślę poprawki, Buzzer również będzie działał,

**Comment by abixadamj** [comment]
To jest już dawno temu rozwiązany problem ;-) Ale pokazuje, że czuwamy.
