### ISSUE TITLE
Error in the file przycisk_swiatla.py

### ISSUE THREAD

**Issue by jasonj2333** [ABIX-Edukacja/PyTechBrain#9]
**Line 10** a,b,c = uklad.przycisk_left(), uklad.przycisk_middle(), uklad.przycisk_right()
**I changed -** a,b,c = uklad.przycisk_lewy(), uklad.przycisk_srodkowy(), uklad.przycisk_prawy()

**Line 21** - uklad.11sygnalizator_zolty('on')
**I changed -** uklad.sygnalizator_zolty('on')

**Comment by abixadamj** [comment]
New, redesigned version of library.
